/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threadrelay;

import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;
/**
 *
 * @author aless
 */
public class FormAtleti extends javax.swing.JFrame implements Observer {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormAtleti.class.getName());
    private JPanel mainP;
    private ArrayList<Atleta> atleti;
    private JProgressBar[] bars;
    protected JButton start;
    /**
     * Creates new form FormAtleti
     */
    public FormAtleti(ManagerAtleti mA) {
        initComponents();
        mainP = new JPanel(new BorderLayout());
        
        JPanel titolo = new JPanel();
        titolo.add(new JLabel("STAFFETTA DEI THREAD"));
        
        
        JPanel barsPanel = new JPanel(new GridLayout(4,1, 20,20));
        bars = new JProgressBar[4];
        
        for(int i = 0; i < 4; i++){
            JProgressBar b = new JProgressBar(0, 100);
            bars[i] = b;
            b.getValue();
            barsPanel.add(b);
        }
        
        /*
        JProgressBar bar1 = new JProgressBar();
        JProgressBar bar2 = new JProgressBar();
        JProgressBar bar3 = new JProgressBar();
        JProgressBar bar4 = new JProgressBar();
        barsPanel.add(bar1);
        barsPanel.add(bar2);
        barsPanel.add(bar3);
        barsPanel.add(bar4);
        */
        
        JPanel nomiPanel = new JPanel(new GridLayout(4,1, 20,20));
        
        nomiPanel.add(new JLabel("atleta 1"));
        nomiPanel.add(new JLabel("atleta 2"));
        nomiPanel.add(new JLabel("atleta 3"));
        nomiPanel.add(new JLabel("atleta 4"));
        
        JPanel buttonPanel = new JPanel(new GridLayout(1,4, 20,20));
        start = new JButton("start");
        start.addActionListener(e -> {
            mA.startGara();
            
        });
        
        
        JButton stop = new JButton("stop");
        stop.addActionListener(e -> {
            mA.stopGara();
            
        });
        JButton pausa = new JButton("pausa");
        JButton riprendi = new JButton("riprendi");
        
        buttonPanel.add(start);
        buttonPanel.add(stop);
        buttonPanel.add(pausa);
        buttonPanel.add(riprendi);
        
        mainP.add(titolo, BorderLayout.NORTH);
        mainP.add(barsPanel, BorderLayout.CENTER);
        mainP.add(new JPanel(), BorderLayout.EAST);
        mainP.add(nomiPanel, BorderLayout.WEST);
        mainP.add(buttonPanel, BorderLayout.SOUTH);
        this.add(mainP);
        this.setSize(400, 400);
    }
    
    
    public void aggiungiObserverGrafica(ArrayList atlets){
        atleti = atlets;
        for(Atleta a : atleti){
            a.addObserver(this);
        }
    }
    
    
    @Override
    public void update(Atleta a) {
        bars[atleti.indexOf(a)].setValue(a.getValore());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
