/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threadrelay;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author lleshi.alessandro
 */
public class ThreadForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ThreadForm.class.getName());
    ThreadManager thM;
    /**
     * Creates new form ThreadForm
     */
    public ThreadForm() {
        initComponents();
        thM = new ThreadManager();
        JPanel mainPanel = new JPanel(new BorderLayout());
        JLabel labelTitle = new JLabel("Staffetta");
        labelTitle.setHorizontalAlignment(SwingConstants.CENTER);
        labelTitle.setVerticalAlignment(SwingConstants.CENTER);
        labelTitle.setFont(new Font("Arial", Font.BOLD, 36));
        JPanel nameBarPanel = new JPanel(new GridLayout(4,1, 50,50));
        nameBarPanel.add(new JLabel("atleta 1"));
        nameBarPanel.add(new JLabel("atleta 2"));
        nameBarPanel.add(new JLabel("atleta 3"));
        nameBarPanel.add(new JLabel("atleta 4"));
        
        JPanel barPanel = new JPanel(new GridLayout(4,1, 50,50));

        JProgressBar bar1 = new JProgressBar();
        JProgressBar bar2 = new JProgressBar();
        JProgressBar bar3 = new JProgressBar();
        JProgressBar bar4 = new JProgressBar();
        barPanel.add(bar1);
        barPanel.add(bar2);
        barPanel.add(bar3);
        barPanel.add(bar4);
        
        JPanel buttonPanel = new JPanel(new GridLayout(1,4, 20, 20));
        JButton button1 = new JButton("avvia");
        button1.addActionListener(e -> {
            thM.start();
        });
        
        JButton button2 = new JButton("stop");
        button2.addActionListener(e -> {
            // TODO: Avvia
        });
        
        JButton button3 = new JButton("pausa");
        button3.addActionListener(e -> {
            // TODO: Avvia
        });
        
        JButton button4 = new JButton("riprendi");
        button4.addActionListener(e -> {
            // TODO: Avvia
        });
        
        
        buttonPanel.add(button1);
        buttonPanel.add(button2);
        buttonPanel.add(button3);
        buttonPanel.add(button4);
        
        mainPanel.add(buttonPanel, BorderLayout.SOUTH);
        mainPanel.add(nameBarPanel, BorderLayout.WEST);
        mainPanel.add(barPanel, BorderLayout.CENTER);
        mainPanel.add(labelTitle, BorderLayout.NORTH);
        
        this.add(mainPanel);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ThreadForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
